services:

  - type: web 
    name: webdis
    runtime: node
    repo: https://github.com/catri-01/ServerlessProjectBlueprint.git
    region: Frankfurt
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: serverlessprojectblueprint
          property: connectionString
    

databases:
  - name : serverlessprojectblueprint
    databaseName : serverlessBluedb
    region: Frankfurt